version: '3.9'
services:
  postgres:
    image: postgres:16
    container_name: iam-postgres
    environment:
      POSTGRES_DB: iamdb
      POSTGRES_USER: iam
      POSTGRES_PASSWORD: iam
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    container_name: iam-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: iam
      MONGO_INITDB_ROOT_PASSWORD: iam
      MONGO_INITDB_DATABASE: iam_audit
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  postgres-data:
  mongo-data:
